### ISSUE TITLE
[Errno 2] No such file or directory: 'data/question2program/train_all_pairs.json'

### ISSUE THREAD

**Issue by alice-cool** [CCIIPLab/DIS#1]
在运行下面的第三行代码报错，能否给个建议，前两行都能运行通，第三个没法运行，有文件不存在问题。
![image](https://github.com/CCIIPLab/DIS/assets/16870890/c463f5fb-b2a7-4ba8-982b-9b4ef7ded335)

with open('{}/{}_pairs.json'.format(args.output, split), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/question2program/train_all_pairs.json'

**Comment by liuyuhangYSY** [comment]
@alice-cool Please make sure `data/question2program` is valid path, maybe you can run the following code: 
`mkdir -p data/question2program`
and then, run the `generate_program_t5.py` script.

**Comment by alice-cool** [comment]
.Thanks for your suggestions .I try it soon



---Original---
From: ***@***.***&gt;
Date: Wed, May 22, 2024 11:29 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CCIIPLab/DIS] [Errno 2] No such file or directory:'data/question2program/train_all_pairs.json' (Issue #1)




 
@alice-cool Please make sure data/question2program is valid path, maybe you can run the following code:
 mkdir -p data/question2program
 and then, run the generate_program_t5.py script.
